/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  originsSidebar: [{type: 'autogenerated', dirName: 'origins'}],
  da2Sidebar: [{type: 'autogenerated', dirName: 'da2'}],
  inquisitionSidebar: [{type: 'autogenerated', dirName: 'inquisition'}],
  dreadwolfSidebar: [{type: 'autogenerated', dirName: 'dreadwolf'}],
  infoSidebar: [{type: 'autogenerated', dirName: 'info'}],
};

module.exports = sidebars;
